const LOGIN = "LOGIN"
const LOGOUT = "LOGOUT"
const HANDLE_CHANGE = "HANDLE_CHANGE"
const GET_USERS = "GET_USERS"
const GET_ITEMS = "GET_ITEMS"
const GET_FOLLOWS = "GET_FOLLOWS"
const GET_OUTFITS = "GET_OUTFITS"
const NEW_USER = "NEW_USER"
const NEW_ITEM = "NEW_ITEM"
const NEW_OUTFIT = "NEW_OUTFIT"
const NEW_FOLLOW = "NEW_FOLLOW"


export {
  LOGIN,
  LOGOUT,
  HANDLE_CHANGE,
  GET_USERS,
  GET_ITEMS,
  GET_FOLLOWS,
  GET_OUTFITS,
  NEW_USER,
  NEW_ITEM,
  NEW_OUTFIT,
  NEW_FOLLOW
}
