const LOGIN = "LOGIN"
const HANDLE_CHANGE = "HANDLE_CHANGE"
const GET_USERS = "GET_USERS"
const GET_ITEMS = "GET_ITEMS"
const GET_FOLLOWS = "GET_FOLLOWS"
const GET_OUTFITS = "GET_OUTFITS"
const ADD_USER = "ADD_USER"

export {
  LOGIN,
  HANDLE_CHANGE,
  GET_USERS,
  GET_ITEMS,
  GET_FOLLOWS,
  GET_OUTFITS,
  ADD_USER
}
