const LOGIN = "LOGIN"
const HANDLE_CHANGE = "HANDLE_CHANGE"
const GET_USERS = "GET_USERS"
const GET_ITEMS = "GET_ITEMS"
const GET_OUTFITS = "GET_OUTFITS"

export {
  LOGIN,
  HANDLE_CHANGE,
  GET_USERS,
  GET_ITEMS,
  GET_OUTFITS
}
